services:
  - type: web
    name: appscreencontrol-server
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install --build-from-source
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_VERSION
        value: 20.18.0
